name:                recipe-compiler
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- text
- containers
- nonempty-containers
- async
- mtl
- optparse-applicative
- optparse-generic
- aeson
- generic-aeson
- megaparsec

default-extensions:
- OverloadedStrings

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  recipe-compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - recipe-compiler

tests:
  recipe-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - recipe-compiler
    - hspec
    - hspec-discover
    - QuickCheck


verbatim:
  cabal-version: 3.0
